import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { BsSuitcase2 } from "react-icons/bs";
import Testimonial from "./testimonial/page";
import { FaScroll } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ml-5`}
      >
        <div className="flex gap-15  mt-5">

            <Link href={'/'}>Home</Link>
            <Link href={'/portfolio'}>Portfolio <span><BsSuitcase2/></span> </Link>
            <Link href={'/testimonial'}>Testimonial<FaScroll/></Link>
            <Link href={'/contact'}>Contact</Link>
            <Link href={'users'}>Users</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
