import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
// import Link from "next/link";
// import { BsSuitcase2 } from "react-icons/bs";
// import Testimonial from "../testimonial/page";
// import { FaScroll } from "react-icons/fa";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       
        <header className="bg-blue-400 p-[1rem]">
          <p>Header</p>
        </header>


        {children}

        <footer className="bg-pink-200 p-[1rem] text-black">footer</footer>
      </body>
    </html>
  );
}
